apiVersion: v1
kind: ConfigMap
metadata:
  name: splunk-licenses
  namespace: splunk
data:
  enterprise.lic: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <license>
      <signature>LXGvLEtWQU0xoAJ9TfBlTLY5XQjTrnwGkrmc5/xdIXqnG3RgcacLjQQxb2Os/orI5FAm7NziMKIEAP8r22oxXPl+vWPGCvBTGZrtSiFpjP8heGIw2Exp3howk3M7x9B2nbGTVPutGMt3EhQuVZBHwWHi2YD2khVP3xRhzlB5Ws7VapOLIR7JB71CUn8Lxi9UYWxCq8um2a1gmAjzE/kL+EZvmXkumqafYOyn04QYDTRDNrvKA9EyPXkiOMhxn0EQTYsMvhDKpfbKfaPxhzNK+s8W4l/xqaK9ihvmmftW/GUvr8ITJ4nYvZzoIVbM/ieb8YfNQp04uG3ROCd2zt5pcQ==</signature>
      <payload>
        <type>enterprise</type>
        <group_id>Enterprise</group_id>
        <quota>10737418240</quota>
        <max_violations>5</max_violations>
        <window_period>30</window_period>
        <creation_time>1592377200</creation_time>
        <label>Splunk Developer Personal License DO NOT DISTRIBUTE</label>
        <expiration_time>1608019199</expiration_time>
        <features>
          <feature>Auth</feature>
          <feature>FwdData</feature>
          <feature>RcvData</feature>
          <feature>LocalSearch</feature>
          <feature>DistSearch</feature>
          <feature>RcvSearch</feature>
          <feature>ScheduledSearch</feature>
          <feature>Alerting</feature>
          <feature>DeployClient</feature>
          <feature>DeployServer</feature>
          <feature>SplunkWeb</feature>
          <feature>SigningProcessor</feature>
          <feature>SyslogOutputProcessor</feature>
          <feature>CanBeRemoteMaster</feature>
        </features>
        <add_ons>
          <add_on name="itsi" type="app">
            <parameter key="size" value="10"/>
          </add_on>
        </add_ons>
        <sourcetypes/>
        <guid>AB67B7AD-83DE-404E-85D5-3CCE26524A82</guid>
      </payload>
    </license>
