---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-heavyforwarder-data
  labels:
    app: splunk
    role: splunk_heavyforwarder
    tier: management
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-heavyforwarder-config
  labels:
    app: splunk
    role: splunk_heavyforwarder
    tier: management
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

