---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-license-data
  labels:
    app: splunk
    role: splunk_license_master
    tier: management
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-license-config
  labels:
    app: splunk
    role: splunk_license_master
    tier: management
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

