---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-master-data
  labels:
    app: splunk
    role: splunk_cluster_master
    tier: management
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-master-config
  labels:
    app: splunk
    role: splunk_cluster_master
    tier: management
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

