apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"},"name":"gp2"},"parameters":{"fsType":"ext4","type":"gp2"},"provisioner":"kubernetes.io/aws-ebs"}
      storageclass.kubernetes.io/is-default-class: "true"
    creationTimestamp: "2019-09-18T17:36:10Z"
    name: gp2
    resourceVersion: "128"
    selfLink: /apis/storage.k8s.io/v1/storageclasses/gp2
    uid: cda30adc-da3a-11e9-92d1-0a017844e672
  parameters:
    fsType: ext4
    type: gp2
    zone: eu-central-1a
  provisioner: kubernetes.io/aws-ebs
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
